//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActive
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan TimeLogin { get; set; }
        public System.TimeSpan TimeLogout { get; set; }
        public string NoLogoutReason { get; set; }
    
        public virtual User User { get; set; }
    }
}
